### ISSUE TITLE
dd: failed to truncate to 13335340032 bytes in output file '/media/raspberry-20221125.img': File too large

### ISSUE THREAD

**Issue by Gayisnotgay** [nanhantianyi/rpi-backup#14]
root@raspberrypi:/home/jtang/rpi-backup-master# cat log.txt -n
     1
     2  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
     3
     4  Hit:1 http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian bullseye InRelease
     5  Get:2 http://mirrors.tuna.tsinghua.edu.cn/raspberrypi bullseye InRelease [23.6 kB]
     6  Fetched 23.6 kB in 1s (20.0 kB/s)
     7  Reading package lists...
     8  Building dependency tree...
     9  Reading state information...
    10  All packages are up to date.
    11
    12  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    13
    14  Reading package lists...
    15  Building dependency tree...
    16  Reading state information...
    17  dosfstools is already the newest version (4.2-1).
    18  kpartx is already the newest version (0.8.5-2).
    19  parted is already the newest version (3.4-1).
    20  rsync is already the newest version (3.2.3-4+deb11u1).
    21  The following package was automatically installed and is no longer required:
    22    libfuse2
    23  Use 'apt autoremove' to remove it.
    24  0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    25
    26  software is ready
    27  create /media/raspberry-20221125.img ...
    28  **dd: failed to truncate to 13335340032 bytes in output file '/media/raspberry-20221125.img': File too large**
    29  start=8192s
    30  end=532479s
    31  end2=532480s
    32  Error: The device /media/raspberry-20221125.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
    33  Error: The device /media/raspberry-20221125.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
    34  Error: The device /media/raspberry-20221125.img is so small that it cannot possibly store a file system or partition table. erhaps you selected the wrong device?
    35  losetup: /media/raspberry-20221125.img: Warning: file is smaller than 512 bytes; the loop device may be useless or invisible for system tools.

**Comment by Gayisnotgay** [comment]
can someone help me about this issue ?

**Comment by Gayisnotgay** [comment]
The solution is formatting your u-disk/sd-card using exFAT format which can be easily supported in both Rasbian and Windows.

**Comment by dengyi-g** [comment]
我用 exFat 格式化了还是不行。
```
software is ready
create /media/yurui/Kingston/rpi-backup.img ...
dd: failed to truncate to 32196947968 bytes in output file '/media/yurui/Kingston/rpi-backup.img': File too large
start=8192s
end=532479s
end2=532480s
Error: The device /media/yurui/Kingston/rpi-backup.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
Error: The device /media/yurui/Kingston/rpi-backup.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
Error: The device /media/yurui/Kingston/rpi-backup.img is so small that it cannot possibly store a file system or partition table.  Perhaps you selected the wrong device?
losetup: /media/yurui/Kingston/rpi-backup.img: Warning: file is smaller than 512 bytes; the loop device may be useless or invisible for system tools.
read error, sector 0
llseek error
llseek error
llseek error
read error, sector 0
read error, sector 0
read error, sector 0
device=/dev/mapper/
partBoot=/dev/mapper/p1
partRoot=/dev/mapper/p2
mkfs.fat 4.2 (2021-01-31)
mkfs.vfat: unable to open /dev/mapper/p1: No such file or directory
/dev/mapper/p1 format success
mke2fs 1.46.2 (28-Feb-2021)
The file /dev/mapper/p2 does not exist and no size was specified.
e2label: No such file or directory while trying to open /dev/mapper/p2
Couldn't find valid filesystem superblock.
/dev/mapper/p2 format success
mount: /mnt: special device /dev/mapper/p1 does not exist.
umount: /mnt: not mounted.
mount: /mnt: special device /dev/mapper/p2 does not exist.
sending incremental file list

中间省略

Number of files: 273,423 (reg: 223,090, dir: 25,308, link: 25,025)
Number of created files: 5 (reg: 3, dir: 2)
Number of deleted files: 321 (reg: 319, dir: 2)
Number of regular files transferred: 18
Total file size: 13,360,174,680 bytes
Total transferred file size: 128,437,713 bytes
Literal data: 128,437,713 bytes
Matched data: 0 bytes
File list size: 589,775
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 136,496,255
Total bytes received: 36,410

sent 136,496,255 bytes  received 36,410 bytes  7,801,866.57 bytes/sec
total size is 13,360,174,680  speedup is 97.85
umount: /mnt: not mounted.
```
